# this workflow runs the unit tests and check that everything is working as expected

name: Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    # Needed for xmake to access the source code
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        actions-cache-folder: '.xmake-cache'

    - name: Build test casses
      run: xmake -yvDb Test

    - name: Run test casses
      run: xmake r Test
